package com.example.multyplay;

import java.util.ArrayList;

public class LangsConstants {

    public static final String ALBANIAN = "Albanian";
    public static final String AMHARIC = "Amharic";
    public static final String ARABIC = "Arabic";
    public static final String ARMENIAN = "Armenian";
    public static final String AZERBAIJANI = "Azerbaijani";
    public static final String BELARUSIAN = "Belarusian";
    public static final String BENGALI = "Bengali";
    public static final String BISLAMA = "Bislama";
    public static final String BOSNIAN = "Bosnian";
    public static final String BULGARIAN = "Bulgarian";
    public static final String CATALAN = "Catalan";
    public static final String CROATIAN = "Croatian";
    public static final String CZECH = "Czech";
    public static final String DANISH = "Danish";
    public static final String DUTCH = "Dutch";
    public static final String ENGLISH = "English";
    public static final String ESTONIAN = "Estonian";
    public static final String FINNISH = "Finnish";
    public static final String FRENCH = "French";
    public static final String GEORGIAN = "Georgian";
    public static final String GERMAN = "German";
    public static final String GREEK = "Greek";
    public static final String CREOLE = "Creole";
    public static final String HEBREW = "Hebrew";
    public static final String HINDI = "Hindi";
    public static final String HUNGARIAN = "Hungarian";
    public static final String ICELANDIC = "Icelandic";
    public static final String INDONESIAN = "Indonesian";
    public static final String IRISH = "Irish";
    public static final String ITALIAN = "Italian";
    public static final String JAPANESE = "Japanese";
    public static final String KAZAKH = "Kazakh";
    public static final String KOREAN = "Korean";
    public static final String KURDISH = "Kurdish";
    public static final String KYRGYS = "Kyrgyz";
    public static final String LAO = "Lao";
    public static final String LATVIAN = "Latvian";
    public static final String LITHUANIAN = "Lithuanian";
    public static final String MACEDONIAN = "Macedonian";
    public static final String MALAGASY = "Malagasy";
    public static final String MALAY = "Malay";
    public static final String MANDARIN = "Mandarin";
    public static final String MENDE = "Mende";
    public static final String MONGOLIAN = "Mongolian";
    public static final String MONTENEGRIN = "Montenegrin";
    public static final String NEPALI = "Nepali";
    public static final String NORWEGIAN = "Norwegian";
    public static final String PERSIAN = "Persian";
    public static final String POLISH = "Polish";
    public static final String PORTUGUESE = "Portuguese";
    public static final String ROMANIAN = "Romanian";
    public static final String RUSSIAN = "Russian";
    public static final String SAMOAN = "Samoan";
    public static final String SERBIAN = "Serbian";
    public static final String SLOVAK = "Slovak";
    public static final String SLOVENE = "Slovene";
    public static final String SOMALI = "Somali";
    public static final String SPANISH = "Spanish";
    public static final String SWAHILI = "Swahili";
    public static final String SWEDISH = "Swedish";
    public static final String TAJIK = "Tajik";
    public static final String THAI = "Thai";
    public static final String TIGRINYA = "Tigrinya";
    public static final String TOK_PISIN = "Tok-Pisin";
    public static final String TURKISH = "Turkish";
    public static final String TURKMEN = "Turkmen";
    public static final String UKRAINIAN = "Ukrainian";
    public static final String URDU = "Urdu";
    public static final String UZBEK = "Uzbek";
    public static final String VIETNAMESE = "Vietnamese";

    public static final Language ALBANIAN_LANG = new Language(ALBANIAN, R.drawable.flag_albanian);
    public static final Language AMHARIC_LANG = new Language(AMHARIC, R.drawable.flag_amharic);
    public static final Language ARABIC_LANG = new Language(ARABIC, R.drawable.flag_arabic);
    public static final Language ARMENIAN_LANG = new Language(ARMENIAN, R.drawable.flag_armenian);
    public static final Language AZERBAIJANI_LANG = new Language(AZERBAIJANI, R.drawable.flag_azerbaijani);
    public static final Language BELARUSIAN_LANG = new Language(BELARUSIAN, R.drawable.flag_belarusian);
    public static final Language BENGALI_LANG = new Language(BENGALI, R.drawable.flag_bengali);
    public static final Language BISLAMA_LANG = new Language(BISLAMA, R.drawable.flag_bislama);
    public static final Language BOSNIAN_LANG = new Language(BOSNIAN, R.drawable.flag_bosnian);
    public static final Language BULGARIAN_LANG = new Language(BULGARIAN, R.drawable.flag_bulgarian);
    public static final Language CATALAN_LANG = new Language(CATALAN, R.drawable.flag_catalan);
    public static final Language CROATIAN_LANG = new Language(CROATIAN, R.drawable.flag_croatian);
    public static final Language CZECH_LANG = new Language(CZECH, R.drawable.flag_czech);
    public static final Language DANISH_LANG = new Language(DANISH, R.drawable.flag_danish);
    public static final Language DUTCH_LANG = new Language(DUTCH, R.drawable.flag_dutch);
    public static final Language ENGLISH_LANG = new Language(ENGLISH, R.drawable.flag_english);
    public static final Language ESTONIAN_LANG = new Language(ESTONIAN, R.drawable.flag_estonian);
    public static final Language FINNISH_LANG = new Language(FINNISH, R.drawable.flag_finnish);
    public static final Language FRENCH_LANG = new Language(FRENCH, R.drawable.flag_french);
    public static final Language GEORGIAN_LANG = new Language(GEORGIAN, R.drawable.flag_georgian);
    public static final Language GERMAN_LANG = new Language(GERMAN, R.drawable.flag_german);
    public static final Language GREEK_LANG = new Language(GREEK, R.drawable.flag_greek);
    public static final Language CREOLE_LANG = new Language(CREOLE, R.drawable.flag_creole);
    public static final Language HEBREW_LANG = new Language(HEBREW, R.drawable.flag_hebrew);
    public static final Language HINDI_LANG = new Language(HINDI, R.drawable.flag_hindi);
    public static final Language HUNGARIAN_LANG = new Language(HUNGARIAN, R.drawable.flag_hungarian);
    public static final Language ICELANDIC_LANG = new Language(ICELANDIC, R.drawable.flag_icelandic);
    public static final Language INDONESIAN_LANG = new Language(INDONESIAN, R.drawable.flag_indonesian);
    public static final Language IRISH_LANG = new Language(IRISH, R.drawable.flag_irish);
    public static final Language ITALIAN_LANG = new Language(ITALIAN, R.drawable.flag_italian);
    public static final Language JAPANESE_LANG = new Language(JAPANESE, R.drawable.flag_japanese);
    public static final Language KAZAKH_LANG = new Language(KAZAKH, R.drawable.flag_kazakh);
    public static final Language KOREAN_LANG = new Language(KOREAN, R.drawable.flag_korean);
    public static final Language KURDISH_LANG = new Language(KURDISH, R.drawable.flag_kurdish);
    public static final Language KYRGYS_LANG = new Language(KYRGYS, R.drawable.flag_kyrgyz);
    public static final Language LAO_LANG = new Language(LAO, R.drawable.flag_lao);
    public static final Language LATVIAN_LANG = new Language(LATVIAN, R.drawable.flag_latvian);
    public static final Language LITHUANIAN_LANG = new Language(LITHUANIAN, R.drawable.flag_lithuanian);
    public static final Language MACEDONIAN_LANG = new Language(MACEDONIAN, R.drawable.flag_macedonian);
    public static final Language MALAGASY_LANG = new Language(MALAGASY, R.drawable.flag_malagasy);
    public static final Language MALAY_LANG = new Language(MALAY, R.drawable.flag_malay);
    public static final Language MANDARIN_LANG = new Language(MANDARIN, R.drawable.flag_mandarin);
    public static final Language MENDE_LANG = new Language(MENDE, R.drawable.flag_mende);
    public static final Language MONGOLIAN_LANG = new Language(MONGOLIAN, R.drawable.flag_mongolian);
    public static final Language MONTENEGRIN_LANG = new Language(MONTENEGRIN, R.drawable.flag_montenegrin);
    public static final Language NEPALI_LANG = new Language(NEPALI, R.drawable.flag_nepali);
    public static final Language NORWEGIAN_LANG = new Language(NORWEGIAN, R.drawable.flag_norwegian);
    public static final Language PERSIAN_LANG = new Language(PERSIAN, R.drawable.flag_persian);
    public static final Language POLISH_LANG = new Language(POLISH, R.drawable.flag_polish);
    public static final Language PORTUGUESE_LANG = new Language(PORTUGUESE, R.drawable.flag_portuguese);
    public static final Language ROMANIAN_LANG = new Language(ROMANIAN, R.drawable.flag_romanian);
    public static final Language RUSSIAN_LANG = new Language(RUSSIAN, R.drawable.flag_russian);
    public static final Language SAMOAN_LANG = new Language(SAMOAN, R.drawable.flag_samoan);
    public static final Language SERBIAN_LANG = new Language(SERBIAN, R.drawable.flag_serbian);
    public static final Language SLOVAK_LANG = new Language(SLOVAK, R.drawable.flag_slovak);
    public static final Language SLOVENE_LANG = new Language(SLOVENE, R.drawable.flag_slovene);
    public static final Language SOMALI_LANG = new Language(SOMALI, R.drawable.flag_somali);
    public static final Language SPANISH_LANG = new Language(SPANISH, R.drawable.flag_spanish);
    public static final Language SWAHILI_LANG = new Language(SWAHILI, R.drawable.flag_swahili);
    public static final Language SWEDISH_LANG = new Language(SWEDISH, R.drawable.flag_swedish);
    public static final Language TAJIK_LANG = new Language(TAJIK, R.drawable.flag_tajik);
    public static final Language THAI_LANG = new Language(THAI, R.drawable.flag_thai);
    public static final Language TIGRINYA_LANG = new Language(TIGRINYA, R.drawable.flag_tigrinya);
    public static final Language TOK_PISIN_LANG = new Language(TOK_PISIN, R.drawable.flag_tok_pisin);
    public static final Language TURKISH_LANG = new Language(TURKISH, R.drawable.flag_turkish);
    public static final Language TURKMEN_LANG = new Language(TURKMEN, R.drawable.flag_turkmen);
    public static final Language UKRAINIAN_LANG = new Language(UKRAINIAN, R.drawable.flag_ukrainian);
    public static final Language URDU_LANG = new Language(URDU, R.drawable.flag_urdu);
    public static final Language UZBEK_LANG = new Language(UZBEK, R.drawable.flag_uzbek);
    public static final Language VIETNAMESE_LANG = new Language(VIETNAMESE, R.drawable.flag_vietnamese);

    public static ArrayList<Language> getAllLangsList() {
        ArrayList<Language> allLangsList = new ArrayList<>();
        allLangsList.add(ALBANIAN_LANG);
        allLangsList.add(AMHARIC_LANG);
        allLangsList.add(ARABIC_LANG);
        allLangsList.add(ARMENIAN_LANG);
        allLangsList.add(AZERBAIJANI_LANG);
        allLangsList.add(BELARUSIAN_LANG);
        allLangsList.add(BENGALI_LANG);
        allLangsList.add(BISLAMA_LANG);
        allLangsList.add(BOSNIAN_LANG);
        allLangsList.add(BULGARIAN_LANG);
        allLangsList.add(CATALAN_LANG);
        allLangsList.add(CROATIAN_LANG);
        allLangsList.add(CZECH_LANG);
        allLangsList.add(DANISH_LANG);
        allLangsList.add(DUTCH_LANG);
        allLangsList.add(ENGLISH_LANG);
        allLangsList.add(ESTONIAN_LANG);
        allLangsList.add(FINNISH_LANG);
        allLangsList.add(FRENCH_LANG);
        allLangsList.add(GEORGIAN_LANG);
        allLangsList.add(GERMAN_LANG);
        allLangsList.add(GREEK_LANG);
        allLangsList.add(CREOLE_LANG);
        allLangsList.add(HEBREW_LANG);
        allLangsList.add(HINDI_LANG);
        allLangsList.add(HUNGARIAN_LANG);
        allLangsList.add(ICELANDIC_LANG);
        allLangsList.add(INDONESIAN_LANG);
        allLangsList.add(IRISH_LANG);
        allLangsList.add(ITALIAN_LANG);
        allLangsList.add(JAPANESE_LANG);
        allLangsList.add(KAZAKH_LANG);
        allLangsList.add(KOREAN_LANG);
        allLangsList.add(KURDISH_LANG);
        allLangsList.add(KYRGYS_LANG);
        allLangsList.add(LAO_LANG);
        allLangsList.add(LATVIAN_LANG);
        allLangsList.add(LITHUANIAN_LANG);
        allLangsList.add(MACEDONIAN_LANG);
        allLangsList.add(MALAGASY_LANG);
        allLangsList.add(MALAY_LANG);
        allLangsList.add(MANDARIN_LANG);
        allLangsList.add(MENDE_LANG);
        allLangsList.add(MONGOLIAN_LANG);
        allLangsList.add(MONTENEGRIN_LANG);
        allLangsList.add(NEPALI_LANG);
        allLangsList.add(NORWEGIAN_LANG);
        allLangsList.add(PERSIAN_LANG);
        allLangsList.add(POLISH_LANG);
        allLangsList.add(PORTUGUESE_LANG);
        allLangsList.add(ROMANIAN_LANG);
        allLangsList.add(RUSSIAN_LANG);
        allLangsList.add(SAMOAN_LANG);
        allLangsList.add(SERBIAN_LANG);
        allLangsList.add(SLOVAK_LANG);
        allLangsList.add(SLOVENE_LANG);
        allLangsList.add(SOMALI_LANG);
        allLangsList.add(SPANISH_LANG);
        allLangsList.add(SWAHILI_LANG);
        allLangsList.add(SWEDISH_LANG);
        allLangsList.add(TAJIK_LANG);
        allLangsList.add(THAI_LANG);
        allLangsList.add(TIGRINYA_LANG);
        allLangsList.add(TOK_PISIN_LANG);
        allLangsList.add(TURKISH_LANG);
        allLangsList.add(TURKMEN_LANG);
        allLangsList.add(UKRAINIAN_LANG);
        allLangsList.add(URDU_LANG);
        allLangsList.add(UZBEK_LANG);
        allLangsList.add(VIETNAMESE_LANG);
        return allLangsList;
    }

}
